### ISSUE TITLE
Wrong Git Example

### ISSUE THREAD

**Issue by mcm-jyl** [AlbanAndrieu/ansible-dns#1]
`git clone https://github.com/alban.andrieu/ansible-eclipse.git`
You probably meant
`git clone https://github.com/alban.andrieu/ansible-dns.git`

**Comment by AlbanAndrieu** [comment]
Thanks a lot.
Generator fixed with commit https://github.com/AlbanAndrieu/ansible-nabla/commit/1340e4b6439dfa13952b9c8d01334053807cb3df
